name: 'elt_project'
version: '1.0.0'
config-version: 2

profile: 'elt_project'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  elt_project:
    staging:
      +materialized: view        # staging → view (her sorgu taze veri)
      +schema: staging
    marts:
      +materialized: table       # marts → table (analitik sorgular hızlı)
      +schema: marts
